In [42]:
import pandas as pd

!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\2401895\AppData\Roaming\Python\Python314\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\2401895\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\2401895\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\2401895\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\2401895\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (3.6.0)

In [43]:
# Célula 2 — Carregamento do dataset

# Opção 1: CSV
df = pd.read_csv("br_seeg_emissoes_brasil.csv")

# Visualizar primeiras linhas
df.head()

,ano,nivel_1,nivel_2,nivel_3,nivel_4,nivel_5,nivel_6,tipo_emissao,gas,atividade_economica,produto,emissao
0,1970,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,230462.17
1,1971,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,226016.30
2,1972,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,220101.20
3,1973,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,214195.56
4,1974,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,186862.84

In [44]:
# Célula 3 — Seleção das colunas relevantes

df = df[["ano", "nivel_1", "gas", "emissao"]]

df.head()

    ano       nivel_1      gas    emissao
0  1970  Agropecuária  CH4 (t)  230462.17
1  1971  Agropecuária  CH4 (t)  226016.30
2  1972  Agropecuária  CH4 (t)  220101.20
3  1973  Agropecuária  CH4 (t)  214195.56
4  1974  Agropecuária  CH4 (t)  186862.84

In [45]:
# Célula 4 — Filtrar apenas emissões de CO2

df_co2 = df[df["gas"] == "CO2 (t)"]

df_co2.head()
df_co2.count()

ano        37550
nivel_1    37550
gas        37550
emissao    30795
dtype: int64

In [46]:
# Célula 5 — Remoção de valores nulos

# df_co2 = df_co2.dropna()

# Verificar se ainda existem valores nulos
# df_co2.isnull().sum()
# df_co2.count()

# Achamos que não é necessário remover os valores nulos, pois eles representam anos ou atividades sem emissões de CO2, o que é relevante para a análise. Portanto, optamos por manter os valores nulos para preservar a integridade dos dados e evitar distorções na análise.

In [47]:
# Célula 6 — Aplicação de One-Hot Encoding

df_encoded = pd.get_dummies(
    # get_dummies é uma função do pandas que converte variáveis categóricas em variáveis dummy (0 ou 1)
    df_co2,
    columns=["nivel_1"],
    drop_first=True  # evita redundância
)

df_encoded.head()

,ano,gas,emissao,nivel_1_Energia,nivel_1_Mudança de Uso da Terra e Floresta,nivel_1_Processos Industriais,nivel_1_Resíduos
14150,1970,CO2 (t),223538.51,False,False,False,False
14151,1971,CO2 (t),225473.06,False,False,False,False
14152,1972,CO2 (t),333445.33,False,False,False,False
14153,1973,CO2 (t),280380.69,False,False,False,False
14154,1974,CO2 (t),315281.04,False,False,False,False

In [48]:
# Célula 7 — Normalização da variável de resposta (Emissão)

df_encoded["Emissao_norm"] = (
    df_encoded["emissao"] - df_encoded["emissao"].min()
) / (
    df_encoded["emissao"].max()
    - df_encoded["emissao"].min()
)

df_encoded.head()

,ano,gas,emissao,nivel_1_Energia,nivel_1_Mudança de Uso da Terra e Floresta,nivel_1_Processos Industriais,nivel_1_Resíduos,Emissao_norm
14150,1970,CO2 (t),223538.51,False,False,False,False,0.129892
14151,1971,CO2 (t),225473.06,False,False,False,False,0.129893
14152,1972,CO2 (t),333445.33,False,False,False,False,0.129938
14153,1973,CO2 (t),280380.69,False,False,False,False,0.129916
14154,1974,CO2 (t),315281.04,False,False,False,False,0.129931

# Modelos de Regressão.

Regressão Linear Multipla.  Multiple Linear Regression (MLR)

In [49]:
# Célula 9 — Divisão dos dados

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
        # test_size=0.2 significa que 20% dos dados serão usados para teste e 80% para treino.
        # random_state=42 é uma semente para garantir que a divisão seja a mesma toda vez que o código for executado, permitindo reprodutibilidade.
)

In [50]:
# Célula 10 — Treinamento da Regressão Linear Múltipla

from sklearn.linear_model import LinearRegression

modelo = LinearRegression()
modelo.fit(X_train, y_train)

ValueError: could not convert string to float: 'CO2 (t)'

In [ ]:
# Célula 10 — Treinamento da Regressão Linear Múltipla

from sklearn.linear_model import LinearRegression

modelo = LinearRegression()
modelo.fit(X_train, y_train)

ValueError: could not convert string to float: 'CO2 (t)'